title: "INF200: Advanced Python Programming at NMBU"
author: Yngve Mardal Moe
email: yngvemoe@nmbu.no
description: > # this means to ignore newlines until "baseurl:"
  The information pages for the Advanced Python Programming (INF200) module
  at the Norwegian University of Life Sciences.

github_username:  yngvem

show_excerpts: true # set to false to remove excerpts on the homepage

remote_theme: thelehhman/texture

texture:
  title: INF200: Advanced Python Programming at NMBU
  tagline: Taught by Yngve Mardal Moe
  date_format: "%-d - %b - %Y"
  
  style: black
  showPicker: false
