title: "INF200"
author: Taught by Yngve Mardal Moe
email: yngvemoe@nmbu.no
description: > # this means to ignore newlines until "baseurl:"
  Advanced Python Programming <br>
  <b>Taught by Yngve Mardal Moe*</b>
github_username:  yngvem


show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-slate
